---
 - name:
   hosts: 
   become: true 
   tasks:
   - name: Change the file ownership, and group.
     ansible.builtin.file:
       path: /tmp/exam-file.conf
       owner: exam
       group: exam 
   
